# - - - - - FRONT - - - - -
index:
    path: /
    controller: App\Controller\FrontController::index

formations:
    path: /tableau-des-formations
    controller: App\Controller\FrontController::formations

filiere:
    path: /filiere-{id}/{title}
    controller: App\Controller\FrontController::filiere

sondages:
    path: /sondages
    controller: App\Controller\FrontController::sondages

sondage:
    path: /sondage/{event}/{title}/{id}
    controller: App\Controller\FrontController::sondage

ulis:
    path: /unite-localise-pour-l-inclusion-scolaire
    controller: App\Controller\FrontController::ulis

mlds:
    path: /mission-de-lutte-contre-le-decrochage-scolaire
    controller: App\Controller\FrontController::mlds

histoire:
    path: /histoire-du-lycee
    controller: App\Controller\FrontController::histoire

    # - - - - - AUTH - - - - -

login:
    path: /connexion
    controller: App\Controller\AuthController::login
    methods: GET|POST

logout:
    path: /logout
    # - - - - - ADMIN - - - - -

#--- Survey
survey:
    path: /admin/survey
    controller: App\Controller\admin\SurveyController::survey

addSurvey:
    path: admin/add-survey
    controller: App\Controller\admin\SurveyController::addSurvey

editSurvey:
    path: admin/edit-survey/{id}
    controller: App\Controller\admin\SurveyController::editSurvey

deleteSurvey:
    path: admin/delete-survey/{id}
    controller: App\Controller\admin\SurveyController::deleteSurvey

resultSurvey:
    path: admin/result-survey/{id}
    controller: App\Controller\admin\SurveyController::resultSurvey

    #--- Question
addQuestion:
    path: admin/edit-survey/{id}/add-question
    controller: App\Controller\admin\SurveyController::addQuestion

editQuestion:
    path: admin/edit-survey/{idSurvey}/edit-question/{idQuestion}
    controller: App\Controller\admin\SurveyController::editQuestion

deleteQuestion:
    path: admin/edit-survey/{id}/delete-question/{idQuestion}
    controller: App\Controller\admin\SurveyController::deleteQuestion

deleteChoice:
  path: admin/edit-survey/{idSurvey}/edit-question/{idQuestion}/delete-choice/{idChoice}
  controller: App\Controller\admin\SurveyController::deleteChoice

#--- Event
event:
    path: /admin/event
    controller: App\Controller\admin\EventController::event

deleteEvent:
    path: /admin/delete-event/{id}
    controller: App\Controller\admin\EventController::deleteEvent

addEvent:
    path: /admin/add-event
    controller: App\Controller\admin\EventController::addEvent

editEvent:
    path: /admin/edit-event/{id}
    controller: App\Controller\admin\EventController::editEvent

#--- Filieres
page:
    path: /admin/liste-des-pages
    controller: App\Controller\admin\PageController::page

page_add:
    path: /admin/ajouter-une-page
    controller: App\Controller\admin\PageController::pageAdd

page_edit:
    path: /admin/editer-une-page/{id}
    controller: App\Controller\admin\PageController::pageEdit

page_delete:
    path: /admin/suppression-filiere/{id}
    controller: App\Controller\admin\PageController::pageDelete

#--- Tableau
tableau_list:
  path: /admin/tableau-des-formations
  controller: App\Controller\admin\TableauController::tableauList

tableau_add:
  path: /admin/ajouter-une-ligne-du-tableau
  controller: App\Controller\admin\TableauController::tableauAdd

tableau_edit:
  path: /admin/editer-une-ligne-du-tableau/{id}
  controller: App\Controller\admin\TableauController::tableauEdit

tableau_delete:
  path: /admin/suppression-ligne-tableau/{id}
  controller: App\Controller\admin\TableauController::tableauDelete

#--- QR Code
qrcodelist:
    path: "admin/qr-codes"
    controller: App\Controller\admin\QRCodeController::index
qrcoderendering:
    path: "admin/qr-codes/rendu"
    controller: App\Controller\admin\QRCodeController::rendering
