# - - - - - FRONT - - - - -
index:
    path: /
    controller: App\Controller\FrontController::index

formations:
    path: /formations
    controller: App\Controller\FrontController::formations

filiere:
    path: /filiere/{id}/{title}
    controller: App\Controller\FrontController::filiere

sondages:
    path: /sondages
    controller: App\Controller\FrontController::sondages

sondage:
    path: /sondages/sondage
    controller: App\Controller\FrontController::sondage

ulis:
    path: /unite-localise-pour-l-inclusion-scolaire
    controller: App\Controller\FrontController::ulis

mlds:
    path: /mission-de-lutte-contre-le-decrochage-scolaire
    controller: App\Controller\FrontController::mlds

histoire:
    path: /histoire-du-lycee
    controller: App\Controller\FrontController::histoire
    
    # - - - - - ADMIN - - - - -


#--- Dashboard
dashboard:
    path: /admin
    controller: App\Controller\admin\AdminController::index

#--- Event
event:
    path: /admin/event
    controller: App\Controller\admin\EventController::event

addEvent:
    path: /admin/addEvent
    controller: App\Controller\admin\EventController::addEvent

editEvent:
    path: /admin/editEvent
    controller: App\Controller\admin\EventController::editEvent

deleteEvent:
    path: /admin/deleteEvent
    controller: App\Controller\admin\EventController::deleteEvent

#--- Survey
survey:
    path: /admin/survey
    controller: App\Controller\admin\SurveyController::survey

addSurvey:
    path: admin/addSurvey
    controller: App\Controller\admin\SurveyController::addSurvey

editSurvey:
    path: admin/editSurvey
    controller: App\Controller\admin\SurveyController::editSurvey

#--- Page
page:
    path: /admin/liste-des-pages
    controller: App\Controller\admin\PageController::page

page_add:
    path: /admin/ajouter-une-page
    controller: App\Controller\admin\PageController::pageAdd

page_edit:
    path: /admin/editer-une-page/{id}
    controller: App\Controller\admin\PageController::pageEdit
