index:
    path: /
    controller: App\Controller\FrontController::index

dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

page:
    path: /admin/page
    controller: App\Controller\AdminController::page

event:
    path: /admin/event
    controller: App\Controller\AdminController::event

survey:
    path: /admin/survey
    controller: App\Controller\AdminController::survey

addEvent:
    path: /admin/addEvent
    controller: App\Controller\AdminController::addEvent