# - - - - - FRONT - - - - -
index:
    path: /
    controller: App\Controller\FrontController::index

formations:
    path: /tableau-des-formations
    controller: App\Controller\FrontController::formations

filiere:
    path: /filiere-{id}/{title}
    controller: App\Controller\FrontController::filiere

sondages:
    path: /sondages
    controller: App\Controller\FrontController::sondages

sondage:
    path: /sondages/sondage
    controller: App\Controller\FrontController::sondage

ulis:
    path: /unite-localise-pour-l-inclusion-scolaire
    controller: App\Controller\FrontController::ulis

mlds:
    path: /mission-de-lutte-contre-le-decrochage-scolaire
    controller: App\Controller\FrontController::mlds

histoire:
    path: /histoire-du-lycee
    controller: App\Controller\FrontController::histoire

    # - - - - - AUTH - - - - -

login:
    path: /connexion
    controller: App\Controller\AuthController::login
    methods: GET|POST

logout:
    path: /logout
    # - - - - - ADMIN - - - - -
dashboard:
    path: /admin
    controller: App\Controller\admin\AdminController::index

event:
    path: /admin/event
    controller: App\Controller\admin\EventController::event

deleteEvent:
    path: /admin/deleteEvent/{id}
    controller: App\Controller\admin\EventController::deleteEvent

#--- Survey
survey:
    path: /admin/survey
    controller: App\Controller\admin\SurveyController::survey

addSurvey:
    path: admin/addSurvey
    controller: App\Controller\admin\SurveyController::addSurvey

addEvent:
    path: /admin/addEvent
    controller: App\Controller\admin\EventController::addEvent

editEvent:
    path: /admin/editEvent/{id}
    controller: App\Controller\admin\EventController::editEvent

editSurvey:
    path: admin/editSurvey/{id}
    controller: App\Controller\admin\SurveyController::editSurvey

deleteSurvey:
    path: admin/deleteSurvey/{id}
    controller: App\Controller\admin\SurveyController::deleteSurvey

resultSurvey:
    path: admin/resultSurvey/{id}
    controller: App\Controller\admin\SurveyController::resultSurvey

#--- Page
page:
    path: /admin/liste-des-pages
    controller: App\Controller\admin\PageController::page

page_add:
    path: /admin/ajouter-une-page
    controller: App\Controller\admin\PageController::pageAdd

page_edit:
    path: /admin/editer-une-page/{id}
    controller: App\Controller\admin\PageController::pageEdit

page_delete:
    path: /admin/suppression-filiere/{id}
    controller: App\Controller\admin\PageController::pageDelete

#--- QR Code
qrcodelist:
    path: "admin/qr-codes"
    controller: App\Controller\admin\QRCodeController::index
qrcoderendering:
    path: "admin/qr-codes/rendu"
    controller: App\Controller\admin\QRCodeController::rendering
