# - - - - - FRONT - - - - -
index:
    path: /
    controller: App\Controller\FrontController::index

formations:
    path: /formations
    controller: App\Controller\FrontController::formations

filiere:
    path: /filiere
    controller: App\Controller\FrontController::filiere

sondages:
    path: /sondages
    controller: App\Controller\FrontController::sondages

sondage:
    path: /sondages/sondage
    controller: App\Controller\FrontController::sondage

ulis:
    path: /unite-localise-pour-l-inclusion-scolaire
    controller: App\Controller\FrontController::ulis

mlds:
    path: /mission-de-lutte-contre-le-decrochage-scolaire
    controller: App\Controller\FrontController::mlds

histoire:
    path: /histoire-du-lycee
    controller: App\Controller\FrontController::histoire
    
    # - - - - - ADMIN - - - - -

dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

event:
    path: /admin/event
    controller: App\Controller\AdminController::event

addEvent:
    path: /admin/addEvent
    controller: App\Controller\AdminController::addEvent

editEvent:
    path: /admin/editEvent
    controller: App\Controller\AdminController::editEvent

deleteEvent:
    path: /admin/deleteEvent
    controller: App\Controller\AdminController::deleteEvent

survey:
    path: /admin/survey
    controller: App\Controller\AdminController::survey

page:
    path: /admin/page
    controller: App\Controller\AdminController::page
